# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish to PyPI

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # build SQLite from source, because I need 3.35<=
      - name: Download SQLite3
        run: |
          wget https://www.sqlite.org/2024/sqlite-autoconf-3450300.tar.gz
          tar -xvf sqlite-autoconf-3450300.tar.gz

      - name: Install SQLite3
        run: |
          ./configure
          make
          sudo make install
          export PATH="/usr/local/lib:$PATH"
        working-directory: sqlite-autoconf-3450300

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest tox
        env:
          LD_LIBRARY_PATH: /usr/local/lib
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with tox
        run: |
          tox
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: Build docs
        run: |
          tox -e docs
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - run: touch ./docs/_build/html/.nojekyll

      - name: GH Pages Deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/_build/html
          clean: true # Automatically remove deleted files from the deploy branch

      - name: Build Project and Publish
        run: |
          python -m tox -e clean,build
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
